data:
  batch_size: 16
  dataset: openwebtext
model:  
  vocab_size: 50257
  embed_dim: 768
  block_size: 1024
  dropout: 0.2
optimization:
  device: cuda:0
  lr: 3e-4
  run_name: 2023-02-02-day-2-gpt-small-openwebtext-adam-dropout-0.2